// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  editorialImage: dynamic(() => import('./EditorialImage')),
  editorialImageGallery: dynamic(() => import('./EditorialImageGallery')),
  embed: dynamic(() => import('./Embed')),
  quote: dynamic(() => import('./Quote')),
  text: dynamic(() => import('./Text')),
  textAndIcons: dynamic(() => import('./TextAndIcons')),
  textAndImage: dynamic(() => import('./TextAndImage')),
};
